### PR TITLE
Added basic layouts support

### PR DESCRIPTION
**Pull request by sshobotov**
@peyerluk please review

### CODE REVIEW

**Comment by peyerluk** [comment]
@sshobotov Can you split the pull-request into multiple commits please? (Especially the files in the `dist/` folder should go into their own commit.

And a description about the added functionality here in this pull-request would be great.

First feedback: It looks like having both a `wrapper` and a `layouts` configuration is a bit much. What's the main difference between the wrapper config and the layouts config?

Plus at the moment nothing is done with the `layoutName` in the `livingdoc` beside serialization.

**Comment by sshobotov** [comment]
About a wrapper and a layouts in configuration, I leave wrapper for backward compatibility that allows to avoid refactor all projects with still using new versions of engine.

About using of layout itself it used here https://github.com/nzzdev/livingdocs-editor/pull/61, but I think it's just first steps.

**Comment by sshobotov** [comment]
@peyerluk please review changes

**Comment by peyerluk** [comment]
Nice. What remains to do is to write a few specs. 

You can add a layout configuration to test_design_json.coffee and add specs to renderer_spec.coffee. There are already specs for the wrapper there.

**Comment by sshobotov** [comment]
@peyerluk please review

**Comment by sshobotov** [comment]
@peyerluk please check

**Comment by sshobotov** [comment]
@peyerluk Version reverted

**Comment by peyerluk** [comment]
Thanks! All good now :) Shall I merge and you make a release?

**Comment by sshobotov** [comment]
would be great

**Pull request merged**
