### PR TITLE
get the nth component from the component tree

### PR DESCRIPTION
**Pull request by DaRaFF**
It would be nice to get the nth component of a component tree (we could use that f.e. in tests in render decorator.

//cc @mheiniger

### CODE REVIEW

**Comment by DaRaFF** [comment]
@peyerluk pls review

**Comment by peyerluk** [comment]
@DaRaFF What's the status?

**Comment by DaRaFF** [comment]
I totally agree but had no time to fix it, will do it today :-)

**Comment by peyerluk** [comment]
No hurry. Just stumbled accross this pr :)

**Comment by DaRaFF** [comment]
@peyerluk ok, i fixed your comments, if you agree, i make a patch release.

**Comment by peyerluk** [comment]
:+1: yes, you can do another release.

**Comment by mheiniger** [comment]
:sunny:

**Pull request merged**
