### PR TITLE
Image directive mimetype

### PR DESCRIPTION
**Pull request by sshobotov**
To use image directive with some internal services mime-type field is needed.

### CODE REVIEW

**Comment by sshobotov** [comment]
@peyerluk please review

**Comment by peyerluk** [comment]
Looks good. But just add a simple spec since this is part of the public API

**Comment by sshobotov** [comment]
@peyerluk please review

**Comment by peyerluk** [comment]
I don't know what happened to this pr. You could either do an interactive rebase or create a fresh branch and cherry pick the three commits you need to fix this.

**Pull request closed without merging**
