### PR TITLE
Expose image services on the browser API

### PR DESCRIPTION
**Pull request by caillou**
@gabrielhase could you review. I'll merge and release it if it's OK.

### CODE REVIEW

**Comment by caillou** [comment]
@gabrielhase should the kind of change be unit tested?

**Comment by gabrielhase** [comment]
Not sure if this is related to this pull-request, but the tests are failing. We should fix that.

**Comment by gabrielhase** [comment]
I don't know what you need the method for, but just to point you at it: if this is something that might also be needed on the server side you also need to add it to `node_api.coffee`

**Comment by caillou** [comment]
@gabrielhase running `npm install` should fix the failing unit-tests.

**Pull request merged**
