### PR TITLE
Field extractor

### PR DESCRIPTION
**Pull request by peyerluk**

### CODE REVIEW

**Comment by gabrielhase** [comment]
@peyerluk thx! At some point you need to show me what you did.

**Comment by gabrielhase** [comment]
@peyerluk This is ready for review.
I didn't implement any optimizations yet. I plan to do this in a separate branch/pull-request.
You can test this with the following editor branch: https://github.com/upfrontIO/livingdocs-editor/pull/249

**Comment by caillou** [comment]
@gabrielhase ready for review.

**Comment by gabrielhase** [comment]
:+1: :gem:

**Pull request merged**
