### PR TITLE
The node version of livingdocs-engine sets a global window variable

### PR DESCRIPTION
**Pull request by marcbachmann**
This conflicts with the elasticsearch library, which tries to load the browser version if there's a window

### CODE REVIEW

**Comment by marcbachmann** [comment]
BaBaam....

**Comment by marcbachmann** [comment]
@peyerluk this is ready to review

**Comment by peyerluk** [comment]
:+1:

**Comment by marcbachmann** [comment]
Thanks. It works in node and also in combination with elasticsearch.

**Pull request merged**
